name: translate_text
description: A simple Dart package to translate text between languages using the MyMemory Translation API. It provides an easy way to integrate translation features into your Dart or Flutter applications.
version: 1.3.0
repository: https://github.com/ahmedtalal/translate_text
homepage: https://web.facebook.com/ahmd.talal.5
environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
 http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
